vjo.ctype("vjo.darwin.domain.finding.home.categories.CatNav").protos({constructs:function(id){var t=this;vjo.reg.register(t,id);t.element=vjo.reg.register(t,id);vjo.evt.attach(t,t.element,"mouseover",t.mouseOver);vjo.evt.attach(t,t.element,"mouseout",t.mouseOut);vjo.evt.attach(t,t.element,"keydown",t.keyPress)},mouseOver:function(e){var t=this;t.hpif=false;e=t.hpge(vjo.evt.target(e));if(t.timer)window.clearTimeout(t.timer);t.timer=window.setTimeout(vjo.hitch(t,function(){t.hpoe(e)}),50)},mouseOut:function(e){var t=
this;t.hpif=false;if(t.timer)window.clearTimeout(t.timer);t.timer=window.setTimeout(vjo.hitch(t,function(){t.hpce()}),50)},keyPress:function(e){var t=this;t.hpif=true;var r=vjo.evt.target(e);var p=t.hpge(r);switch(e.keyCode){case 37:if(t.hpre&&t.hpre==p){var li=r.parentNode;var lis=li.parentNode.childNodes;var idx=t.hpgi(lis,li);if(idx==0)t.hpce();else t.hprf(li,lis,idx,13,false)}break;case 38:if(t.hpre&&t.hpre==p){li=r.parentNode;lis=li.parentNode.childNodes;idx=t.hpgi(lis,li);if(idx==0)t.hpce();
else t.hprf(li,lis,idx,1,false);t.hppd(e)}break;case 40:if(t.hpre&&t.hpre==p){li=r.parentNode;lis=li.parentNode.childNodes;idx=t.hpgi(lis,li);if(idx==lis.length-1)t.hpce();else t.hprf(li,lis,idx,1,true);t.hppd(e);break}case 39:if(t.hpre&&t.hpre==p){li=r.parentNode;lis=li.parentNode.childNodes;idx=t.hpgi(lis,li);if(idx==lis.length-1)t.hpce();else t.hprf(li,lis,idx,13,true);t.hppd(e);break}var h2=t.hptn(r.parentNode)=="h2"?r.parentNode:false;li=r.parentNode.parentNode;if(t.hptn(r)=="a"&&h2&&!/hpcl/.test(li.className)){t.hpoe(li);
t.hppd(e)}break;case 27:if(t.hpre)t.hpce();break}},hpge:function(e){for(var i=0;!/hpcn/.test(e.parentNode.className)&&i<10;){e=e.parentNode;i++}return i<10?e:null},hpoe:function(e){var t=this;if(t.hpre)t.hpce();t.hpre=e;e.className+=" hpcl";if(t.hpif)e.lastChild.firstChild.firstChild.focus()},hpce:function(){var t=this;if(t.hpre)t.hpre.className=t.hpre.className.replace(/(\s?hpcl\s?)+/,"");if(t.hpif)t.hpre.firstChild.firstChild.focus();t.hpre=null},hptn:function(e){return e.tagName.toLowerCase()},
hpgi:function(lis,li){for(var i=0;i<lis.length;i++)if(lis[i]==li)return i},hprf:function(li,lis,idx,p,l){if(this.hptn(li)=="li"){if(l)idx=idx+p>lis.length-1?lis.length-1:idx+p;else idx=idx-p>0?idx-p:0;lis[idx].firstChild.focus()}},hppd:function(e){if(e.preventDefault)e.preventDefault();else e.returnValue=false}}).endType();
vjo.ctype("vjo.darwin.domain.finding.home.hputils.HPUtils").props({toVI:function(id,_2,_3){var _4;var _5;_4=vjo.dsf.Element.get(id);_5=vjo.dsf.Element.get(_2);if(_4&&_5){_4.onmouseover();if(_5.href.indexOf("ebayrtm")<0)_5.href=_4.href;if(_3)window.location=_4.href}},wrapUrl:function(id,_7){var _8=vjo.get(id);if(_8&&_8.href.indexOf("ebayrtm")<0)_8.href=_7},hpr:function(id){var _a=new Image;var e;var tr="";var clk;e=vjo.dsf.Element.get(id);var ul=e.parentNode.parentNode;if(ul){tr=ul.getAttribute("tr");
clk=e.getAttribute("clk");if(tr&&tr!="null"&&clk&&clk!="null"){e.href=e.href+tr+clk;_a.src=e.getAttribute("url")+"&redirect=false"}}return true},hpo:function(id){var e;e=vjo.dsf.Element.get(id);e.href=e.getAttribute("url")}}).inits(function(){window.toVI=vjo.darwin.domain.finding.home.hputils.HPUtils.toVI;window.wrapUrl=vjo.darwin.domain.finding.home.hputils.HPUtils.wrapUrl;window.hpr=vjo.darwin.domain.finding.home.hputils.HPUtils.hpr;window.hpo=vjo.darwin.domain.finding.home.hputils.HPUtils.hpo}).endType();
vjo.ctype("vjo.darwin.domain.finding.home.roll.FilmRoll").protos({constructs:function(_1){var t=this;t.m=_1;t.vis=false;t.count=0;t.total=0;t.anchor=vjo.get(t.m.uId);t.lbut=vjo.get(t.m.lbId),t.rbut=vjo.get(t.m.rbId),t.frmc=vjo.get(t.m.tbId);t.cur=0,t.n=t.m.cards,t.s=t.m.w/t.m.cards;if(t.lbut&&t.rbut&&t.frmc){vjo.evt.attach(t,t.frmc,"keydown",t.keyboardNav);vjo.evt.attach(t,t.lbut,"mouseover",t.onLeftHover);vjo.evt.attach(t,t.rbut,"mouseover",t.onRightHover);vjo.evt.attach(t,t.lbut,"mouseout",t.onLeftOut);
vjo.evt.attach(t,t.rbut,"mouseout",t.onRightOut);vjo.evt.attach(t,t.lbut,"click",t.onLeftClick);vjo.evt.attach(t,t.rbut,"click",t.onRightClick)}if(parseInt(t.m.cards)<=parseInt(t.m.NI))t.rbut.className="hpa-rbt"},keyboardNav:function(e){var t=this;var _5=vjo.utl.getTags(t.frmc,"li","icell");var _6=vjo.utl.getAncestor(t.frmc,"div","hpfm");if(e.keyCode===9){t.count++;t.total++;if(t.m.NI>=5&&t.count===t.m.NI*2&&t.total<_5.length*2){t.onRightClick();t.count=0}else if(t.m.NI===1&&t.count===2&&t.total<
_5.length*2){t.onRightClick();t.frmc.style.left="-3200px";t.count=0}else if(!_6&&t.m.NI===2&&t.count===2&&t.total<_5.length){t.onRightClick();t.frmc.style.left="-150px";t.count=0}else if(_6&&t.m.NI===2&&t.count===2&&t.total<_5.length){t.onRightClick();t.frmc.style.left="-150px";t.count=0}}},onLeftHover:function(){if(this.lbut.className.match("hpa-lbt-a"))this.lbut.className="hpa-lbt-h"},onRightHover:function(){if(this.rbut.className.match("hpa-rbt-a"))this.rbut.className="hpa-rbt-h"},onLeftOut:function(){if(this.lbut.className.match("hpa-lbt-h"))this.lbut.className=
"hpa-lbt-a"},onRightOut:function(){if(this.rbut.className.match("hpa-rbt-h"))this.rbut.className="hpa-rbt-a"},move:function(){var t=this;var dir;if(!t.vis)t.loadImgs();if(t.pre<t.cur)dir=1;else dir=0;t.pmove(t.pre*t.m.w,t.m.w/10,dir)},loadImgs:function(){var t=this;t.vis=true;var _9=vjo.utl.getTags(t.frmc,"img");var i=0;for(var j=_9.length;i<j;i++)if(_9[i].getAttribute("xrc")){_9[i].src=_9[i].getAttribute("xrc");_9[i].removeAttribute("xrc")}},pmove:function(_b,_c,_d){var t=this;if(_d==1&&_b>=t.m.w*
t.cur-_c||_d==0&&_b<=t.m.w*t.cur+_c){t.setLeft(t.m.w*t.cur);return false}var _f=_b;if(_d==1)_f+=_c;else _f-=_c;t.setLeft(_f);setTimeout(function(){t.pmove(_f,_c,_d)},10)},setLeft:function(lft){this.frmc.style.left=0-lft+"px"},onLeftClick:function(){var t=this;if(t.lbut.className.match("hpa-lbt-h")){t.pre=t.cur;t.cur--;if(t.anchor)t.replaceSugg(t.cur);t.move();if(t.cur==0)t.lbut.className="hpa-lbt";t.rbut.className="hpa-rbt-a"}},onRightClick:function(){var t=this;if(t.rbut.className.match("hpa-rbt-h")||
t.count>0){t.pre=t.cur;t.cur++;if(t.anchor)t.replaceSugg(t.cur);t.move();if(t.cur==Math.ceil(parseInt(t.m.cards)/parseInt(t.m.NI))-1)t.rbut.className="hpa-rbt";t.lbut.className="hpa-lbt-a"}},replaceSugg:function(p){var t=this;t.anchor.href=t.m.u[p];t.anchor.innerHTML=t.m.isCSA[p]?t.m.linkC:t.m.linkO}}).endType();
vjo.ctype("vjo.darwin.domain.finding.home.countdown.CountDown").protos({constructs:function(_1){var t=this;t.m=_1},remaintimer:function(){var t=this;var rt=vjo.get(t.m.rtId);var cdp=vjo.get(t.m.htmlId);if(rt===null||rt===undefined){try{if(console){console.info("rt is null t.m.rtId"+t.m.rtId+"t.sHtmlId :"+t.m.htmlId);console.info(rt)}}catch(e){}return}var _4=new Date;var _5=new Date;_4.setFullYear(_5.getUTCFullYear());_4.setMonth(_5.getUTCMonth());_4.setDate(_5.getUTCDate());_4.setHours(_5.getUTCHours());
_4.setMinutes(_5.getUTCMinutes());_4.setSeconds(_5.getUTCSeconds());var _6=new Date;_6.setFullYear(t.m.year);_6.setMonth(t.m.month);_6.setDate(t.m.days);_6.setHours(t.m.hours);_6.setMinutes(t.m.minutes);_6.setSeconds(t.m.seconds);var _7=Math.round(_6.valueOf()-_4.valueOf());var nS=Math.floor(_7/1E3);var nM=Math.floor(nS/60);nS=nS%60;var nH=Math.floor(nM/60);nM=nM%60;var nD=Math.floor(nH/60);nH=nH%60;if(nD>0||nH>0||nM>0||nS>0){nD=nD<0?"00":nD<10?"0"+nD:nD;nH=nH<0?"00":nH<10?"0"+nH:nH;nM=nM<0?"00":
nM<10?"0"+nM:nM;nS=nS<0?"00":nS<10?"0"+nS:nS;if(nD>0)rt.innerHTML=nD+t.m.d+nH+t.m.h+nM+t.m.m+nS+t.m.s;else if(nH>0)rt.innerHTML=nH+t.m.h+nM+t.m.m+nS+t.m.s;else if(nM>0)rt.innerHTML=nH+t.m.h+nM+t.m.m+nS+t.m.s;else rt.innerHTML=nH+t.m.h+nM+t.m.m+nS+t.m.s;if(this.cdid)window.clearTimeout(this.cdid);this.cdid=window.setTimeout(vjo.hitch(this,this.remaintimer),1E3)}else{rt.innerHTML=t.m.endedLabel;if(this.cdid)window.clearTimeout(this.cdid)}},countFlash:function(){var rt=this.E.get(this.m.rtId);rt.innerHTML=
"<span class='cdbg'>00</span><span class='cdtimeunit'>s </span>";if(this.flashid)window.clearTimeout(this.flashid)}}).endType();
vjo.ctype("vjo.darwin.domain.finding.home.rtm.OnLoadHandler").needs("vjo.dsf.utils.Handlers","vh").needs("vjo.dsf.Element","E").protos({constructs:function(_1){var t=this;var o=t.vj$;t.cfg=_1;t.cont=o.E.get(t.cfg.id);o.vh.attachEvt(window,"load",t.publish,t)},publish:function(){var t=this;if(t.cfg.pids){vjo.svc.sendRequest("RTM_LOAD_PIDS",{pids:t.cfg.pids,fL:true});return}if(t.cont!=null)if(t.cont.className!="wdw wdw")t.cont.innerHTML=t.cfg.stuff}}).endType();
vjo.ctype("vjo.darwin.domain.jaguar.home.billboard.BillBoard").protos({cache:[],dur:1500,inv:4E3,res:1E3,state:0,pos:0,loc:false,limit:3,RTMTimeOut:2500,isRTMTimeOut:false,useFilter:false,isIE7:false,constructs:function(_1){var t=this;var b=vjo.dsf.client.Browser;t.$=vjo.dsf.Element.get;t.m=_1;t.el=t.$(t.m.id);t.bb_el=t.el.childNodes;t.nv_el=t.el.parentNode.getElementsByTagName("ul");t.nv=t.nv_el[t.nv_el.length-1];t.nv_el=t.nv.childNodes;t.fC=t.nv_el.length;t.useFilter=b.bIE&&b.iVer<9?true:false;
t.isIE7=b.bIE&&b.iVer==7?true:false},rui:function(){var t=this;var cPos=t.pos+1;if(cPos==t.fC)cPos=0;t.setMultiOptions(cPos);if(cPos==0)t.limit--;if(t.limit<1)t.si()},si:function(t){t=this;clearInterval(t.start);try{clearTimeout(t.resume)}catch(e){}},ri:function(t$$0){t$$0=this;if(t$$0.limit>0)t$$0.resume=setTimeout(vjo.hitch(t$$0,function(t){t=this;if(t.cache[0]==false)t.rui();t.start=setInterval(vjo.hitch(t,t.rui),t.inv)}),t$$0.res)},callRTM:function(){var t=this;var c=vjo.dsf.cookie.VjCookieJar.readCookie("npii",
"cguid");var u=t.m.rtmUrl;if(t.fC>1){u+="&ord="+(new Date).getTime();u+="&cg="+(c?c:(new Date).getTime());vjo.evt.attach(t,t.el,"mouseover",t.si);vjo.evt.attach(t,t.el,"mouseout",t.ri);vjo.evt.attach(t,t.nv,"mouseover",t.si);vjo.evt.attach(t,t.nv,"mouseout",t.ri);t.ri();vjo.dsf.assembly.VjClientAssembler.load(new vjo.dsf.assembly.VjClientAssemblerRequest(u,t.render,t,"cb",false));setTimeout(vjo.hitch(t,t.handleRTMTimeout),t.RTMTimeOut)}return false},handleRTMTimeout:function(t){t=this;if(!t.isRTMTimeOut){t.isRTMTimeOut=
true;for(var i=0;i<t.fC-1;i++)t.cache.push('<iframe src="'+t.m.defaultUrl.replace("#",i+1)+'" width="825" height="271" frameborder="no" border="0" marginwidth="0" marginheight="0" scrolling="no">');t.assignMenu()}},render:function(_a,t){t=this;if(!t.isRTMTimeOut&&_a&&_a.length>0&&_a[0].content!=""){t.isRTMTimeOut=true;var _c=_a.length;var jn;if(_a[_c-1].CSSMetaData){var s=_a[_c-1].CSSMetaData.CSSURLs;for(j in s)vjo.dsf.utils.CssLoader.load(s[j])}var _e;var _f;var _10;var el;var re=new RegExp('<img.*?src="http://srx([^"]*?)".*?>',
"ig");for(var i=0;i<t.fC-1;i++){jn=_a[i];if(jn&&jn.content){_e=jn.content;_10=re.exec(_e);if(_10){el=t.bb_el[i+1];el.style.display="none";el.innerHTML=_e.replace(_10[0],"");t.cache.push(_10[0])}else t.cache.push(_e)}else t.cache.push('<iframe src="'+t.m.defaultUrl.replace("#",i+1)+'" width="825" height="271" frameborder="no" border="0" marginwidth="0" marginheight="0" scrolling="no">')}t.assignMenu()}},assignMenu:function(t){t=this;for(i in t.nv_el)if(i<t.fC)vjo.evt.attach(t,t.nv_el[i],"click",t.navClick)},
setMultiOptions:function(_15,t){t=this;t.inEl=t.bb_el[_15];t.outEl=t.bb_el[t.pos];t.fadeTimeLeft=t.dur;t.lastTick=t.newTick();t.cPos=_15;t.loc=true;t.inEl.style.display="block";t.numMultiNavClz();if(t.useFilter)t.animateMultiFilter();else t.animateMulti()},numMultiNavClz:function(t){t=this;t.nv_el[t.cPos].className="mfbs";t.nv_el[t.pos].className="";if(t.cPos>0&&t.cache[t.cPos-1]){t.inEl.innerHTML+=t.cache[t.cPos-1];t.executeScripts(t.inEl.innerHTML);t.cache[t.cPos-1]=false}},executeScripts:function(_18){var re=
/<script\b[\s\S]*?>([\s\S]*?)<\/script>/ig;var m=re.exec(_18);if(m)vjo.dsf.utils.JsLoader.loadText(m[1])},animateMulti:function(t){t=this;t.currentTick=t.newTick();var _1b=t.returnElapsedTicks();var helper=function(){t.animateMulti()};if(t.fadeTimeLeft<=_1b){t.inEl.style.opacity=1;t.outEl.style.opacity=0;t.outEl.style.display="none";t.pos=t.cPos;t.loc=false;return}t.fadeTimeLeft-=_1b;var _1c=t.fadeTimeLeft/t.dur;t.inEl.style.opacity=1-_1c;t.outEl.style.opacity=_1c;t.lastTick=t.currentTick;t.currentTick=
t.newTick();setTimeout(vjo.hitch(t,helper),33)},animateMultiFilter:function(t){t=this;t.currentTick=t.newTick();var _1e=t.returnElapsedTicks();var helper=function(){t.animateMultiFilter()};if(t.fadeTimeLeft<=_1e){t.inEl.style.filter="alpha(opacity=100)";t.outEl.style.filter="alpha(opacity=0)";t.inEl.style.removeAttribute("filter");t.outEl.style.display="none";t.pos=t.cPos;t.loc=false;return}t.fadeTimeLeft-=_1e;var _1f=t.fadeTimeLeft/t.dur;t.inEl.style.filter="alpha(opacity="+(1-_1f)*100+")";t.outEl.style.filter=
"alpha(opacity="+_1f*100+")";t.lastTick=t.currentTick;t.currentTick=t.newTick();setTimeout(vjo.hitch(t,helper),33)},navClick:function(e,t){t=this;t.dur=500;t.si();var el=vjo.evt.target(e);if(!t.loc){var _23=el.innerHTML*1-1;if(t.pos!=_23)t.setMultiOptions(_23)}},newTick:function(){return(new Date).getTime()},returnElapsedTicks:function(t){t=this;return t.currentTick-t.lastTick}}).props({toggle:function(el){el.style.display=el.style.display=="block"?"none":"block"},ctrImg:function(el,s,img){img=new Image;
img.src=el.src;var w=img.width;var h=img.height;var m;if(w<s||h<s){el.style.position="absolute";if(s>w){m=(s-w)/2;if(el.width>w)m*=w/el.width;el.style.left+=m+"px"}if(s>h){m=(s-h)/2;if(el.height>h)m*=h/el.height;el.style.top+=m+"px"}}},shbb:function(e){var t=vjo.darwin.domain.jaguar.home.billboard.BillBoard;var c=0;var ev=e||window.event;for(var el=ev.nativeEvent.target||ev.nativeEvent.srcElement;c<10&&el&&el.tagName&&el.tagName.toLowerCase()!="li";){el=el.parentNode;c++}if(c<10&&el&&el.tagName&&
el.tagName.toLowerCase()=="li"&&!/db-ctdn/.test(el.className)){t.toggle(el.getElementsByTagName("a")[0]);t.toggle(el.getElementsByTagName("div")[0])}},shtc:function(e$$0){var t$$0=vjo.darwin.domain.jaguar.home.billboard.BillBoard;var c=0;var ev=e$$0||window.event;for(var el=ev.nativeEvent.target||ev.nativeEvent.srcElement;c<10&&el&&el.tagName&&el.tagName.toLowerCase()!="li";){el=el.parentNode;c++}if(c<10&&el&&el.className&&el.className.length){el.getElementsByTagName("div")[0].style.display="block";
el.getElementsByTagName("a")[0].style.display="block";try{el.getElementsByTagName("p")[0].style.display="block"}catch(e$$1){}el.onmouseout=function(t){t=this;t.getElementsByTagName("div")[0].style.display="none";t.getElementsByTagName("a")[0].style.display="none";try{t.getElementsByTagName("p")[0].style.display="none"}catch(e){}};el.onmouseover=function(t){t=this;t.getElementsByTagName("div")[0].style.display="block";t.getElementsByTagName("a")[0].style.display="block";try{t.getElementsByTagName("p")[0].style.display=
"block"}catch(e){}};el.onclick=function(){location=this.getElementsByTagName("a")[0].getAttribute("href")}}}}).endType();
vjo.ctype("vjo.darwin.domain.finding.home.footer.HPFooterJaguar").protos({constructs:function(_1){var t=this;t.m=_1;t.flg=vjo.get(t.m.id),t.lyr=vjo.get(t.m.lyrId);if(t.flg){t.btn=t.flg.parentNode;t.e=vjo.reg.register(t,t.m.id);vjo.evt.attach(t,t.btn,"mouseover",t.onShowMenu);vjo.evt.attach(t,t.lyr,"mouseover",t.onShowMenu);vjo.evt.attach(t,t.btn,"mouseout",t.onHideMenu);vjo.evt.attach(t,t.lyr,"mouseout",t.onHideMenu)}},onShowMenu:function(_3){var t=this;t.lyr.style.display="block";t.lyr.style.top=
vjo.px(vjo.utl.offsetTop(t.btn)-t.lyr.offsetHeight+1);t.lyr.style.left=vjo.px(vjo.utl.offsetLeft(t.btn)-t.lyr.offsetWidth+t.btn.offsetWidth)},onHideMenu:function(){var t=this;t.lyr.style.display="none"}}).endType();
