var slot,debug,adserver_url;if(typeof adserver_url=="undefined"){var httpx=document.location.protocol;adserver_url=httpx+"//pda-as.amazon.com/getad"}var adFetchTimer,adFetchStartTime,AD_FETCH_TIMEOUT_MS=1E4,tracker;function logerr(){}function isFirefox(){return navigator.userAgent.match(/Firefox/)}
function findUIBlockToTrack(){var a,b=window;for(a=window;b!=top;b=b.parent)a=b;if(isFirefox())for(var b=top.document.getElementsByTagName("iframe"),c=0;c<b.length;c++){var d=b[c];if(d.contentWindow==a)return d}else{b=top.frames;for(c=0;c<b.length;c++)if(a==b[c])return top.document.getElementsByTagName("iframe")[c]}return null}function createFunctionInvoker(a,b,c,d,e,f,g){return function(){a(b,c,d,e,f,g)}}function createInvoker(a,b){return function(){a[b]()}}
function A9AdsView(a,b){this.adsUIBlock=a;this.topWindow=top;if(this.adsUIBlock)this.checking=null,this.setupAdLookingEvents(),this.scheduleVisibleCheck(),this.dataSent=false,this.document=top.document,this.viewUrl=decodeURIComponent(b);else throw"Could not find the block";}
A9AdsView.prototype.setupAdLookingEvents=function(){var a=this.topWindow;a.addEventListener?(a.addEventListener("resize",createInvoker(this,"scheduleVisibleCheck"),false),a.addEventListener("scroll",createInvoker(this,"scheduleVisibleCheck"),false)):a.attachEvent&&(a.attachEvent("onresize",createInvoker(this,"scheduleVisibleCheck")),a.attachEvent("onscroll",createInvoker(this,"scheduleVisibleCheck")))};
A9AdsView.prototype.removeAdLookingEvents=function(){var a=this.topWindow;a.removeEventListener?(a.removeEventListener("resize",createInvoker(this,"scheduleVisibleCheck"),false),a.removeEventListener("scroll",createInvoker(this,"scheduleVisibleCheck"),false)):a.detachEvent&&(a.detachEvent("onresize",createInvoker(this,"scheduleVisibleCheck")),a.detachEvent("onscroll",createInvoker(this,"scheduleVisibleCheck")))};
function A9AdsFindDivPosition(a){var b=0,c=0;if(a.offsetParent){do b+=a.offsetLeft,c+=a.offsetTop;while(a=a.offsetParent)}return[b,c]}function A9AdsGetScrollTop(a){return a.documentElement.scrollTop||a.body.scrollTop}function A9AdsGetClientHeight(a){return a.documentElement.clientHeight!=0&&a.body.clientHeight!=0?a.body.clientHeight<=a.documentElement.clientHeight?a.body.clientHeight:a.documentElement.clientHeight:a.body.clientHeight?a.body.clientHeight:a.documentElement.clientHeight}
A9AdsView.prototype.areAdsVisible=function(){var a=this.adsUIBlock,b=A9AdsGetScrollTop(this.document),c=b+A9AdsGetClientHeight(this.document),d=A9AdsFindDivPosition(a)[1],a=d+a.scrollHeight;return d<=c&&b<=a};A9AdsView.prototype.checkAdsViewable=function(){if(this.dataSent!=true&&this.areAdsVisible(this.adsUIBlock)&&this.dataSent!=true)this.dataSent=true,setTimeout(createInvoker(this,"checkAdsStillVisible"),250)};
A9AdsView.prototype.checkAdsStillVisible=function(){if(this.areAdsVisible()){var a=this.document.createElement("script");a.type="text/javascript";a.src=this.viewUrl;this.document.body.insertBefore(a,this.document.body.firstChild);this.removeAdLookingEvents()}else this.dataSent=false};A9AdsView.prototype.scheduleVisibleCheck=function(){if(this.dataSent!=true){if(this.checking)clearTimeout(this.checking),this.checking=null;this.checking=setTimeout(createInvoker(this,"checkAdsViewable"),100)}};
function setAdIntoAANResponse(a){a={adId:a.adId,creativeId:a.creativeId,adNetwork:"PDA"};if(!top.document.aanResponse)top.document.aanResponse={};top.document.aanResponse[slot+"adData"]=a}function publisherActivities(a){try{logerr("in publisher activities");var b=findUIBlockToTrack();b?(setAdIntoAANResponse(a),tracker=new A9AdsView(b,a.viewUrl)):logerr("Could not find ui block to track")}catch(c){logerr(c)}}
function parseUrlParams(){for(var a=document.location.href.replace(/^[^#]*#/,""),a=a.split("&"),b=0;b<a.length;b++){var c=a[b].split("=");c.length==2&&(c[0]=="s"?slot=c[1]:c[0]=="d"&&(debug=c[1]))}}
function punt(){typeof pda_disable_punt!=="undefined"&&pda_disable_punt===true?window.d16gCollapse=true:document.referrer!=null&&document.referrer.indexOf("cdn-bpx.a9.com")!=-1?document.write('<script src="http://cdn-bpx.a9.com/amzn/defaultad.js"><\/script>'):document.write('<script src="http://bpx.a9.com/amzn/defaultad.js"><\/script>')}function haveRequiredValues(){return typeof slot==="undefined"?false:true}
function getAanParams(a){for(var b=window,c,d=0;d<10;d++){try{if(typeof b.aanParams!="undefined"){c=b.aanParams;break}}catch(e){logerr(e)}if(b==b.parent)break;b=b.parent}return typeof c==="undefined"?null:c[a]}
function addToRunOnLoad(a,b){if(!a.addRunOnLoad)a.runOnLoadEvents=[],a.addRunOnLoad=function(b){a.runOnLoadEvents.push(b)},a.runOnLoadActual=function(b){a.addRunOnLoad=function(a){a()};for(var d=0;d<a.runOnLoadEvents.length;d++){b=a.runOnLoadEvents[d];try{b()}catch(e){}}},a.setTimeout(a.runOnLoadActual,1E3);a.addRunOnLoad(b)}
function pda_render_ad(a){adFetchTimer&&(clearTimeout(adFetchTimer),adFetchTimer=null);if(!a||!a.html||a.html.length==0)punt();else if(document.write(a.html),document.close(),a.viewUrl)try{logerr("Adding to run on load"),addToRunOnLoad(top,createFunctionInvoker(publisherActivities,a,slot))}catch(b){logger(b)}else logerr("No View Url")}function fetchAds(a){document.write("<script src='"+(adserver_url+"?"+a)+"'><\/script>");document.close()}function pda_do_not_render_ad(){window.d16gCollapse=true}
function adFetchTimerCB(){(new Date).getTime()-adFetchStartTime<AD_FETCH_TIMEOUT_MS||(pda_render_ad=pda_do_not_render_ad,punt())}function startAdsTimer(){adFetchStartTime=(new Date).getTime();adFetchTimer=setTimeout(adFetchTimerCB,AD_FETCH_TIMEOUT_MS)}function main(){parseUrlParams();if(haveRequiredValues()){var a=getAanParams(slot);a?(fetchAds(a),startAdsTimer()):punt()}else punt()}main();
